import "../lib/startup.i"
import "../lib/stdlib.i"

main() {
    var s;
    # S will contain pointer to string literal
    s = "Example string";

    printf("Hello, world!\r\n");

    # Parse number with specified base
    printf("\r\nNum parsers: %b\r\n", parse_num("11100111", 2));

    printf("Formatter: %%d: %d %%o: %o %%x: %x %%s: %s\r\n", parse_dec("-00123z"), parse_oct("-5656"), parse_hex("AbCdEf"), s);
}